/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas.modul2;

/**
 *
 * @author Windows 10
 */
public class gajikaryawan extends javax.swing.JFrame {
    public int jmkerja,tarifjm, gjbruto,jamlembur, gajilembur,pajak,gjbersih;
    /**
     * Creates new form gajikaryawan
     */
    public gajikaryawan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        titik1 = new javax.swing.JLabel();
        titik2 = new javax.swing.JLabel();
        jamkerja = new javax.swing.JLabel();
        tarif = new javax.swing.JLabel();
        bgajibruto = new javax.swing.JButton();
        isijamkerja = new javax.swing.JTextField();
        isitarif = new javax.swing.JTextField();
        gajibruto = new javax.swing.JLabel();
        isigajibruto = new javax.swing.JTextField();
        bgajibersih = new javax.swing.JButton();
        gajibersih = new javax.swing.JLabel();
        isigajibersih = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        judul.setFont(new java.awt.Font("Bodoni MT Black", 3, 24)); // NOI18N
        judul.setText("GAJI KARYAWAN");

        titik1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        titik1.setText("--------------------------------------------------------------------------------");

        titik2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        titik2.setText("--------------------------------------------------------------------------------");

        jamkerja.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jamkerja.setText("Jumlah Jam Kerja 1 Minggu  :");

        tarif.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tarif.setText("Tarif Per-jam                         :");

        bgajibruto.setBackground(new java.awt.Color(0, 255, 0));
        bgajibruto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bgajibruto.setText("Hitung Gaji Bruto");
        bgajibruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgajibrutoActionPerformed(evt);
            }
        });

        isijamkerja.setBackground(new java.awt.Color(204, 204, 255));
        isijamkerja.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        isijamkerja.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        isijamkerja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        isijamkerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isijamkerjaActionPerformed(evt);
            }
        });

        isitarif.setBackground(new java.awt.Color(204, 204, 255));
        isitarif.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        isitarif.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        isitarif.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        isitarif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isitarifActionPerformed(evt);
            }
        });

        gajibruto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gajibruto.setText("Gaji Bruto                             :");

        isigajibruto.setBackground(new java.awt.Color(204, 204, 255));
        isigajibruto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        isigajibruto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        isigajibruto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        isigajibruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isigajibrutoActionPerformed(evt);
            }
        });

        bgajibersih.setBackground(new java.awt.Color(0, 255, 0));
        bgajibersih.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bgajibersih.setText("Hitung Gaji Bersih");
        bgajibersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgajibersihActionPerformed(evt);
            }
        });

        gajibersih.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        gajibersih.setText("Gaji Bersih                            :");

        isigajibersih.setBackground(new java.awt.Color(204, 204, 255));
        isigajibersih.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        isigajibersih.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        isigajibersih.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        isigajibersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isigajibersihActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titik1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titik2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jamkerja)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(isijamkerja, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addComponent(judul))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(tarif)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(isitarif, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(bgajibruto))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(gajibruto)
                            .addGap(18, 18, 18)
                            .addComponent(isigajibruto, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(gajibersih)
                        .addGap(18, 18, 18)
                        .addComponent(isigajibersih, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(bgajibersih)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(judul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titik1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titik2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jamkerja)
                    .addComponent(isijamkerja, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tarif)
                    .addComponent(isitarif, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(bgajibruto)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isigajibruto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gajibruto))
                .addGap(18, 18, 18)
                .addComponent(bgajibersih)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isigajibersih, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gajibersih))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isijamkerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isijamkerjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isijamkerjaActionPerformed

    private void isitarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isitarifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isitarifActionPerformed

    private void isigajibrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isigajibrutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isigajibrutoActionPerformed

    private void isigajibersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isigajibersihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isigajibersihActionPerformed

    private void bgajibrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgajibrutoActionPerformed
        jmkerja = Integer.parseInt(isijamkerja.getText());
        tarifjm = Integer.parseInt(isitarif.getText());
        if (jmkerja <= 40){
            gjbruto = jmkerja * tarifjm;
        }
        else {
            jamlembur = jmkerja - 40;
            gajilembur = (int)(jamlembur * (tarifjm * 1.5));
            gjbruto = 40 * tarifjm + gajilembur;
        }
        isigajibruto.setText(String.valueOf(gjbruto));
    }//GEN-LAST:event_bgajibrutoActionPerformed

    private void bgajibersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgajibersihActionPerformed
        pajak = (int)(0.1 * gjbruto);
        gjbersih = gjbruto - pajak;
        isigajibersih.setText(String.valueOf(gjbersih));
    }//GEN-LAST:event_bgajibersihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gajikaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gajikaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gajikaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gajikaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gajikaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bgajibersih;
    private javax.swing.JButton bgajibruto;
    private javax.swing.JLabel gajibersih;
    private javax.swing.JLabel gajibruto;
    private javax.swing.JTextField isigajibersih;
    private javax.swing.JTextField isigajibruto;
    private javax.swing.JTextField isijamkerja;
    private javax.swing.JTextField isitarif;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jamkerja;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel tarif;
    private javax.swing.JLabel titik1;
    private javax.swing.JLabel titik2;
    // End of variables declaration//GEN-END:variables
}
