/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas.modul2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows 10
 */
public class warungg extends javax.swing.JFrame {
    String menuu;
    int Harga, Jumlah, Total;
    public warungg() {
        initComponents();
        jumlah.setText("" + Jumlah);
        tambah.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                Jumlah++;
                jumlah.setText(Integer.toString(Jumlah));
            }
        });
        kurangi.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                if (Jumlah > 0){
                    Jumlah --;
                    jumlah.setText(Integer.toString(Jumlah));
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        logo1 = new javax.swing.JLabel();
        logo2 = new javax.swing.JLabel();
        judul1 = new javax.swing.JLabel();
        judul2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        nasgor = new javax.swing.JRadioButton();
        bakso = new javax.swing.JRadioButton();
        nasiuduk = new javax.swing.JRadioButton();
        miegoreng = new javax.swing.JRadioButton();
        pecel = new javax.swing.JRadioButton();
        soto = new javax.swing.JRadioButton();
        rawon = new javax.swing.JRadioButton();
        mieayam = new javax.swing.JRadioButton();
        menuu1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        juduljumlah = new javax.swing.JLabel();
        tambah = new javax.swing.JButton();
        kurangi = new javax.swing.JButton();
        jumlah = new javax.swing.JTextField();
        detail = new javax.swing.JLabel();
        bpesan = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        namamenu = new javax.swing.JLabel();
        lharga = new javax.swing.JLabel();
        ljumlah = new javax.swing.JLabel();
        ltotal = new javax.swing.JLabel();
        isimenu = new javax.swing.JLabel();
        isiharga = new javax.swing.JLabel();
        isijumlah = new javax.swing.JLabel();
        isitotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/modul2/logo1.png"))); // NOI18N

        logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas/modul2/logo2.png"))); // NOI18N

        judul1.setFont(new java.awt.Font("Georgia", 3, 30)); // NOI18N
        judul1.setText("WARUNG");

        judul2.setFont(new java.awt.Font("Georgia", 3, 30)); // NOI18N
        judul2.setText("VAVA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(judul1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(judul2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(logo2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(judul1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(judul2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(logo2)
                    .addComponent(logo1))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(nasgor);
        nasgor.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        nasgor.setText("Nasi Goreng");
        nasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nasgorActionPerformed(evt);
            }
        });

        buttonGroup1.add(bakso);
        bakso.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        bakso.setText("Bakso");
        bakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baksoActionPerformed(evt);
            }
        });

        buttonGroup1.add(nasiuduk);
        nasiuduk.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        nasiuduk.setText("Nasi Uduk");

        miegoreng.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        miegoreng.setText("Mie Goreng");

        buttonGroup1.add(pecel);
        pecel.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        pecel.setText("Pecel Lele");

        buttonGroup1.add(soto);
        soto.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        soto.setText("Soto Lamongan");

        buttonGroup1.add(rawon);
        rawon.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        rawon.setText("Rawon");
        rawon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rawonActionPerformed(evt);
            }
        });

        buttonGroup1.add(mieayam);
        mieayam.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        mieayam.setText("Mie Ayam");

        menuu1.setFont(new java.awt.Font("Elephant", 3, 18)); // NOI18N
        menuu1.setText("Menu Makanan");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nasgor)
                            .addComponent(nasiuduk, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(miegoreng, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pecel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bakso)
                            .addComponent(soto)
                            .addComponent(rawon)
                            .addComponent(mieayam)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(menuu1)
                        .addGap(72, 72, 72)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menuu1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nasgor)
                    .addComponent(bakso))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nasiuduk)
                    .addComponent(soto))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(miegoreng)
                    .addComponent(rawon))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mieayam)
                    .addComponent(pecel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        juduljumlah.setFont(new java.awt.Font("Elephant", 3, 18)); // NOI18N
        juduljumlah.setText("Jumlah Pesanan");

        tambah.setBackground(new java.awt.Color(51, 255, 0));
        tambah.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        tambah.setText("+");
        tambah.setMaximumSize(new java.awt.Dimension(30, 30));
        tambah.setMinimumSize(new java.awt.Dimension(30, 30));
        tambah.setPreferredSize(new java.awt.Dimension(30, 30));

        kurangi.setBackground(new java.awt.Color(255, 0, 0));
        kurangi.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        kurangi.setText("-");

        jumlah.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jumlah.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });

        detail.setFont(new java.awt.Font("Elephant", 3, 18)); // NOI18N
        detail.setText("Detail Pesanan");

        bpesan.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        bpesan.setText("Pesan");
        bpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpesanActionPerformed(evt);
            }
        });

        bhapus.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        namamenu.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        namamenu.setText("Nama Makanan :");

        lharga.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        lharga.setText("Harga                   :");

        ljumlah.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        ljumlah.setText("Jumlah Beli        :");

        ltotal.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        ltotal.setText("Total Beli            :");

        isimenu.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        isimenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        isimenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        isimenu.setPreferredSize(new java.awt.Dimension(54, 23));

        isiharga.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        isiharga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        isiharga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        isiharga.setPreferredSize(new java.awt.Dimension(54, 23));

        isijumlah.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        isijumlah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        isijumlah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        isijumlah.setPreferredSize(new java.awt.Dimension(54, 23));

        isitotal.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        isitotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        isitotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        isitotal.setPreferredSize(new java.awt.Dimension(54, 23));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(kurangi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jumlah, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bpesan)
                        .addGap(29, 29, 29)
                        .addComponent(bhapus)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(juduljumlah))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(detail))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(namamenu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isimenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lharga)
                                .addGap(5, 5, 5)
                                .addComponent(isiharga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(ltotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isitotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(ljumlah)
                                .addGap(4, 4, 4)
                                .addComponent(isijumlah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(juduljumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kurangi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bpesan)
                    .addComponent(bhapus))
                .addGap(18, 18, 18)
                .addComponent(detail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namamenu)
                    .addComponent(isimenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lharga)
                    .addComponent(isiharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ljumlah)
                    .addComponent(isijumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(isitotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ltotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nasgorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nasgorActionPerformed

    private void baksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baksoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baksoActionPerformed

    private void rawonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rawonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rawonActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void bpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpesanActionPerformed
        if (nasgor.isSelected()){
            menuu = "Nasi Goreng";
            Harga = 10000;
        } else if(nasiuduk.isSelected()){
            menuu = "Nasi Uduk";
            Harga = 12000;
        } else if(miegoreng.isSelected()){
            menuu = "Mie Goreng";
            Harga = 7000;
        } else if(pecel.isSelected()){
            menuu = "Pecel";
            Harga = 7000;
        } else if(bakso.isSelected()){
            menuu = "Bakso";
            Harga = 10000;
        } else if(soto.isSelected()){
            menuu = "Soto Lamongan";
            Harga = 8000;
        } else if(rawon.isSelected()){
            menuu = "Rawon";
            Harga = 8000;
        } else if(mieayam.isSelected()){
            menuu = "Mie Ayam";
            Harga = 10000;
        } else{
            JOptionPane.showMessageDialog(this,"Silahkan Pilih Menu","ERROR",JOptionPane.ERROR_MESSAGE);
        }

        Jumlah = Integer.parseInt(jumlah.getText());
        if (Jumlah > 0){
            Total = Jumlah * Harga;
            isimenu.setText(menuu);
            isiharga.setText(String.valueOf(Harga));
            isijumlah.setText(String.valueOf(Jumlah));
            isitotal.setText(String.valueOf(Total));
        } else{
            JOptionPane.showMessageDialog(this,"Silahkan Tambah Jumlah Beli","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        

    }//GEN-LAST:event_bpesanActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        jumlah.setText("");
        buttonGroup1.clearSelection();
        isimenu.setText("");
        isiharga.setText("");
        isijumlah.setText("");
        isitotal.setText("");
    }//GEN-LAST:event_bhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(warungg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(warungg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(warungg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(warungg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new warungg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bakso;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bpesan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel detail;
    private javax.swing.JLabel isiharga;
    private javax.swing.JLabel isijumlah;
    private javax.swing.JLabel isimenu;
    private javax.swing.JLabel isitotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel judul1;
    private javax.swing.JLabel judul2;
    private javax.swing.JLabel juduljumlah;
    private javax.swing.JTextField jumlah;
    private javax.swing.JButton kurangi;
    private javax.swing.JLabel lharga;
    private javax.swing.JLabel ljumlah;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel logo2;
    private javax.swing.JLabel ltotal;
    private javax.swing.JLabel menuu1;
    private javax.swing.JRadioButton mieayam;
    private javax.swing.JRadioButton miegoreng;
    private javax.swing.JLabel namamenu;
    private javax.swing.JRadioButton nasgor;
    private javax.swing.JRadioButton nasiuduk;
    private javax.swing.JRadioButton pecel;
    private javax.swing.JRadioButton rawon;
    private javax.swing.JRadioButton soto;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
